### ISSUE TITLE
[Bug]: temps de lancement de Shake

### ISSUE THREAD

**Issue by florian-lefebvre** [EduWireApps/ynotes#110]
### Description du bug

Depuis la 0.13.4, faire un retour met beaucoup de temps (avec Shake).

### Etapes à reproduire

1. Ouvrir le drawer
2. Appuyer sur "Faire un retour"
3. Attendre

### Comportement attendu

Il faudrait que la page de report s'ouvre plus vite ou montrer un loader.

### Appareil

Samsung Galaxy A10

### OS

Android 11

### Version

0.13.4

### Environnement

Public

### Service scolaire

EcoleDirecte

### Contexte supplémentaire

@JsonLinesCode est-ce que le sdk v15 est plus rapide ?

**Comment by JsonLinesCode** [comment]
Aucun rapport avec le SDK c'est le packaging (interne) des logs qui prend un peu de temps
