### ISSUE TITLE
!non

### ISSUE THREAD

**Issue by Androz2091** [EduWireApps/ynotes#116]
🤖 Cette issue a été ouverte depuis un message sur Discord https://discord.com/channels/734693484149080135/838039639737499672/908306237194653736

Le cloud est buggé, il vaut mieux utiliser ED directement pour cette fonctionnalité pour le moment

**Comment by florian-lefebvre** [comment]
Fail de @JsonLinesCode

**Comment by JsonLinesCode** [comment]
😅
