### ISSUE TITLE
[Feature]: Marquer aussi les devoirs comme faits sur la plateforme

### ISSUE THREAD

**Issue by killianeletellier** [EduWireApps/ynotes#128]
### Votre demande de fonctionnalité est-elle liée à un problème ? Veuillez le décrire.

Non applicable.

### Décrivez la solution que vous souhaitez

Actuellement, les devoirs ne sont marqués comme faits que sur l'application. Je pense qu'il pourrait être pratique de répercuter ce changement sur la plateforme (EcoleDirecte ou Pronote).

**Comment by JsonLinesCode** [comment]
Duplicate de #36
