### ISSUE TITLE
Scroller jusqu'à l'heure en cours dans l'emploi du temps

### ISSUE THREAD

**Issue by LiteApplication** [EduWireApps/ynotes#144]
### Description du problème

L'emploi du temps déborde à la verticale, obligeant l'utilisateur à scroller pour afficher l'heure de cours actuelle.

### Description de l'amélioration

Deux possibilités pour améliorer la situation :
 - Faire en sorte que l'emploi du temps tienne sur une page (pas pratique avec beaucoup d'heures de cours)
 - scroller par défaut jusqu'à l'heure actuelle

### Contexte supplémentaire

J'ai remarqué que l'emploi du temps est plus utilisé par mes amis et moi-même pour voir les heures à venir que les heures passées.
Il est donc plus intuitif de voir directement l'heure actuelle et l'heure future que les heures de cours de la matinée.
Cela se place dans la perspective de rendre encore plus simple l'accès à l'emploi du temps tel qu'indiqué dans #78

**Comment by florian-lefebvre** [comment]
Un rework de l'agenda est prévu pour la 0.16, sans date de release prévue pour le moment.

**Comment by LiteApplication** [comment]
D'accord, je verrai si j'arrive à implémenter la fonctionnalité pour réduire un peu votre charge de travail
