### ISSUE TITLE
Connexion par webview charge à l'infini

### ISSUE THREAD

**Issue by Androz2091** [EduWireApps/ynotes#22]
La connexion par webview charge à l'infini après la saisie des identifiants dans la webview (testé sur Android avec le cas mon-ent-occitanie, cela fonctionne bien avec quelques autres CAS que j'ai pu également tester).

**Comment by ModernChocolate** [comment]
Semble relatif à un simple problème de timing dû à une mauvaise connexion. Un fix sera quand même déployé pour empêcher la reproduction du bug.

**Comment by Androz2091** [comment]
Issue probablement liée à #35.
