### ISSUE TITLE
Problème de padding dans les paramètres

### ISSUE THREAD

**Issue by Androz2091** [EduWireApps/ynotes#23]
Le padding semble cassé dans les paramètres de l'appli. J'ai fait un fix sur [EduWireApps/flutter-settings-ui](https://github.com/EduWireApps/flutter-settings-ui), peut-être que ça peut régler ce pb ?

![Screenshot_20210421_103653](https://user-images.githubusercontent.com/42497995/115523654-94795480-a28d-11eb-8832-0431ad10f20a.jpg)

**Comment by florian-lefebvre** [comment]
@ModernChocolate où ça en est ?

**Comment by ModernChocolate** [comment]
Corrigé, sera disponible dans la prochaine release
