### ISSUE TITLE
Affichage d'une fenêtre blanche lors de l'ouverture du mode partage d'un devoir non synchronisé.

### ISSUE THREAD

**Issue by Androz2091** [EduWireApps/ynotes#29]
🤖 Cette issue a été ouverte depuis un message sur Discord https://discord.com/channels/734693484149080135/838039639737499672/839140245319843851

L'affichage en mode partage d'un devoir non synchronisé provoque l'affichage d'une fenêtre blanche.

**Comment by florian-lefebvre** [comment]
@ModernChocolate avec le nouveau design, est-ce qu'il y aura encore ce problème ?

**Comment by ModernChocolate** [comment]
Corrigé durant la migration en null safety.
