### ISSUE TITLE
Pas de .ipa dans les releases

### ISSUE THREAD

**Issue by florian-lefebvre** [EduWireApps/ynotes#30]
Is this normal ? They are .apk files but not IOS ones

**Comment by ModernChocolate** [comment]
Les .ipa nécessitent un sideloading par le biais d'un utilitaire tiers, ce qui est dans tous les cas très peu accessible. C'est inutile avec la présence de l'application sur l'App Store et il est plus intéressant de compiler soi-même la version voulue en cas de nécessité.
