### ISSUE TITLE
Impossible d'entrer des caractères spéciaux sur lycée connecté

### ISSUE THREAD

**Issue by Mr-KayJayDee** [EduWireApps/ynotes#31]
Après avoir entré le lien de mon Pronote, j'atterris sur la page de connexion lycée connecté et quand je veut entrer mes identifiants je ne peut pas entrer de caractères spéciaux, quand je clique sur le bouton caractères spéciaux de mon clavier ça Switch directement sur le clavier de lettre. (Embêtant pour les mots de passe)

Étapes pour reproduire le comportement :
1. Ouvrir Ynote
2. Choisir Pronote
3. Choisir "Saisir l'URL"
4. Entrer l'URL Pronote (https://0160048r.index-education.net/pronote/eleve.html)
5. Cliquer se connecter
6. Quand la page est chargé, essayer d'entrer l'identifiant, le mien comporte un tiret et je ne peut pas l'entrer, et mon mot de passe a des caractères spéciaux.

**Comportement attendu**
Possibilité d'entrer dans les zones textuelles des caractères spéciaux.

**Captures d'écran**
https://youtube.com/shorts/syjyCyDLlPc?feature=share

**Smartphone:**
 - Appareil : Oneplus 6
 - OS : Android 11, RQ2A.210305.006
PixelExperience_Plus_enchilada-11.0-20210313-1827-UNOFFICIAL

**Comment by ModernChocolate** [comment]
Duplicate of #21.
