### ISSUE TITLE
Utiliser Pronote pour marquer les devoirs comme faits

### ISSUE THREAD

**Issue by Androz2091** [EduWireApps/ynotes#36]
Actuellement, le comportement de l'appli semble être de garder en mémoire locale le fait qu'un devoir soit fait ou non. Cela est un peu embêtant avec plusieurs appareils, et je pense que l'API de Pronote pourrait être utilisée pour marquer le devoir comme fait **sur Pronote**, et récupérer cette info au moment de rafraichir les données.

**Comment by ModernChocolate** [comment]
Comment gérer les devoirs marqués comme non lus hors ligne ? Rafraichir détruirait les devoirs marqués faits hors ligne sur l'application, ou alors toujours privilégier ce qui a été fait hors ligne (c'est actuellement possible vu l'architecture utilisée) ?

**Comment by taokann** [comment]
Bonsoir, je me permets d'intervenir ici puisque c'est un peu moi qui ait orienté la fonctionnalité dans ce sens.
Le souci est que les devois marqués comme faits sur Pronote sont visibles des professeurs, y compris si vous les cochez à un horaire (ahem) tardif.
En résultent des situations assez inconvenantes en classe : "tiens, voyons qui n'a pas fait le devoir...".
On pourrait ajouter une option « synchroniser » désactivable par l'utilisateur mais cela compliquerait le fonctionnement.

**Comment by ModernChocolate** [comment]
Cette fonctionnalité serait évidemment une option activable ou non par l'utilisateur (et par défaut désactivée), mais nécessite une attention particulière quant au "merging" des évènements.

**Comment by florian-lefebvre** [comment]
Cette fonctionnalité ne sera pas intégrée pour le moment car elle ne fait pas partie de nos priorités. Néanmoins, il n'est pas exclu que l'on se penche à nouveau sur la question dans le futur.
