### ISSUE TITLE
Devoirs personnalisés

### ISSUE THREAD

**Issue by Androz2091** [EduWireApps/ynotes#37]
Il pourrait être intéressant de rajouter des tâches/devoirs personnalisées, comme pour l'agenda sur yNotes. Certains devoirs ne sont pas référencés par les enseignants sur Pronote, mais ils sont pour autant bien présents et il me semble intéressant de pouvoir tout centraliser dans l'appli.

**Comment by florian-lefebvre** [comment]
Cette fonctionnalité est disponible depuis la 0.12.
