### ISSUE TITLE
Responsive Design

### ISSUE THREAD

**Issue by Yan-Jobs** [EduWireApps/ynotes#46]
Heyyyyyyy tout le monde ! 
Sur iPad l’affichage est type iPhone (voir screenshot), et c’est très énervant 😡 à lire même si l’app est super !
Merci de votre lecture !
`" Yan Jobs#0001`

![](https://cdn.yanjobs.me/cdn/pic/screenYnotes2.png)

![](https://cdn.yanjobs.me/cdn/pic/screenYnotes1.png)

![](https://cdn.yanjobs.me/cdn/pic/screenYnotes3.png)

![](https://cdn.yanjobs.me/cdn/pic/screenYnotes4.png)

**Comment by florian-lefebvre** [comment]
Hey @Yan-Jobs ! Merci d'ouvrir une issue !
Nous en sommes en train de travailler pour adapter l'appli à toutes les tailles d'écran, mais ça va prendre un peu de temps.

**Comment by Yan-Jobs** [comment]
Heyyyy super merci du retour !

**Comment by florian-lefebvre** [comment]
Hey @Yan-Jobs l'app devrait être responsive à partir de la 0.12 qui devrait sortir ce soir en beta si tout se passe comme prévu.

**Comment by Yan-Jobs** [comment]
> Hey @Yan-Jobs l'app sera responsive à partir de la 0.12 qui devrait sortir ce soir en beta si tout se passe comme prévu.

Coucou 👋,
Et comment je l’ai ? (Sinon gg pour le travail) !

**Comment by Yan-Jobs** [comment]
@florian-lefebvre

**Comment by florian-lefebvre** [comment]
Mmmh la beta est bien sur Android mais sur IOS je sais pas comment ça marche... 😅 @ModernChocolate comment ça se passe ?

**Comment by Yan-Jobs** [comment]
Ah c’est avec TestFlight et tu dois créer un groupe donc… C’est chiant :joy:

**Comment by florian-lefebvre** [comment]
Bon et bien je suppose qu'il faudra attendre la release sur le channel public alors ! Ce sera pas trop longtemps après normalement.

**Comment by Yan-Jobs** [comment]
Ok 👍 souper et le « pas trop longtemps » c’est quoi 😂 ?

**Comment by Yan-Jobs** [comment]
La docu de TestFlight : https://developer.apple.com/testflight/

**Comment by florian-lefebvre** [comment]
> Ok 👍 souper et le « pas trop longtemps » c’est quoi 😂 ?

Honnêtement je ne sais pas, @ModernChocolate te dira.

**Comment by florian-lefebvre** [comment]
En tout cas dès que ce sera dispo, hésite pas à faire des retours soit in-app soit ici pour qu'on puisse améliorer le responsive 👍

**Comment by Yan-Jobs** [comment]
Ok souper 👍

**Comment by Yan-Jobs** [comment]
@ModernChocolate si cela t’intéresse : https://flutter.dev/docs/deployment/ios#release-your-app-on-testflight

**Comment by ModernChocolate** [comment]
Bonjour, oui j'utilise déjà testflight merci pour la doc. Si tout se passe bien je pousse directement en release sur iOS (surtout que le temps d'examen est très long).

**Comment by Yan-Jobs** [comment]
Ok 👍 super merci 🤩 !

**Comment by Yan-Jobs** [comment]
La majorité n’est toujours pas là 😭

**Comment by ModernChocolate** [comment]
J'y travaille patience ! :sweat_smile: De toute manière les examens Apple comme indiqués précédemment peuvent prendre jusqu'à une journée de délai. Donc compte plutôt pour une arrivée de la MàJ dans la semaine...

**Comment by Yan-Jobs** [comment]
> J'y travaille patience ! :sweat_smile: De toute manière les examens Apple comme indiqué précédemment peuvent prendre jusqu'à une journée de délai. Donc compte plutôt pour une arrivée de la MàJ dans la semaine... 

@ModernChocolate Okk 😢

**Comment by Yan-Jobs** [comment]
Heyyyya,
Après l'update le look a un peu (beaucoup) changé vers le positif mais reste une barre où s'arrête l'application (je pense que c'est moins énervant de fix ça que les autres trucs). Je vous met le screen en PJ.

![](https://cdn.yanjobs.me/cdn/pic/screenYnotes5.png)

![](https://cdn.yanjobs.me/cdn/pic/screenYnotes6.png)

**Comment by ModernChocolate** [comment]
Qu'est ce que c'est que ces notes sur 0 ?

**Comment by Yan-Jobs** [comment]
Ce sont les compétences mais je n'ai pas encore report 2s mdrrr 😂

**Comment by Yan-Jobs** [comment]
@ModernChocolate tu peux la voir ici: #

**Comment by florian-lefebvre** [comment]
> Heyyyya,
> Après l'update le look a un peu (beaucoup) changé vers le positif mais reste une barre où s'arrête l'application (je pense que c'est moins énervant de fix ça que les autres trucs). Je vous met le screen en PJ.
> 
> ![](https://cdn.yanjobs.me/cdn/pic/screenYnotes5.png)
> 
> ![](https://cdn.yanjobs.me/cdn/pic/screenYnotes6.png)

Hey @Yan-Jobs ! Je n'ai pas bien compris de quelle barre tu parles, pourrais tu apporter des précisions ? (En mettant une flèche pas exemple)

**Comment by Yan-Jobs** [comment]
La jpp faire un nouveau screen mais c'est que mon iPad fait tout l'écran et le logo GH etc s'arrête avant la fin.

**Comment by florian-lefebvre** [comment]
@Yan-Jobs à l'emplacement de ma flèche rouge ?
![image](https://user-images.githubusercontent.com/69633530/123407112-e1d6b280-d5ab-11eb-8039-2c6029f592f6.png)

**Comment by Yan-Jobs** [comment]
> @Yan-Jobs à l'emplacement de ma flèche rouge ?
> 
> ![image](https://user-images.githubusercontent.com/69633530/123407112-e1d6b280-d5ab-11eb-8039-2c6029f592f6.png)
> 
> 

@florian-lefebvre oui

**Comment by florian-lefebvre** [comment]
@JsonLinesCode tu pourras débuguer ça avec le widget inspector sur ton iPad ? Perso je soupçonne la SafeArea

**Comment by Yan-Jobs** [comment]
Super 👍

**Comment by JsonLinesCode** [comment]
Ce problème a été corrigé il y a peu et si ce n'est toujours pas disponible sur iOS pour l'instant cela le sera bientôt.
