### ISSUE TITLE
Ecran blanc sur iOS

### ISSUE THREAD

**Issue by JsonLinesCode** [EduWireApps/ynotes#56]
# 🐛 Signaler un bug

## Décrire le bug

Stuck sur  un écran blanc au démarrage de l'application.

## Reproduire ce bug

Étapes pour reproduire le comportement :
1. Démarrer l'application sur un appareil physique iOS (cela semble aléatoire mais l'erreur a particulièrement eu lieu sur iPhone 6s)

## Comportement attendu

Démarrage correct

## Smartphone (veuillez compléter les informations suivantes)

 - Appareil : iPhone 6s
 - OS :  iOS 14.5
 - Version: 0.12

## Contexte supplémentaire

 - Application scolaire : Peu importe

**Comment by ModernChocolate** [comment]
Semble lié à https://github.com/flutter/flutter/issues/22188
