### ISSUE TITLE
Problème de chargement des devoirs personnalisés

### ISSUE THREAD

**Issue by Androz2091** [EduWireApps/ynotes#79]
🤖 Cette issue a été ouverte depuis un message sur Discord https://discord.com/channels/734693484149080135/838039639737499672/884475943324884992

Les devoirs personnalisé ne se chargent pas si on ne recharge pas la page des devoirs après l'avoir ouverte

**Comment by florian-lefebvre** [comment]
Problème déjà résolu dans une précédente version.
