### ISSUE TITLE
Accès aux fichiers Android 11

### ISSUE THREAD

**Issue by JsonLinesCode** [EduWireApps/ynotes#93]
# 💅 Amélioration

## Décrire le problème

Suivre le protocole décrit par Google pour bien suivre les règles relatives à l'accès aux fichiers sous Android 11 :

https://support.google.com/googleplay/android-developer/answer/10467955

**Comment by florian-lefebvre** [comment]
```dart
await Permission.manageExternalStorage.request();
```

**Comment by florian-lefebvre** [comment]
L'autorisation a été rajouté au manifest et setup sur le Play Store, il ne reste plus qu'à implémenter la demande d'autorisation in-app.

**Comment by florian-lefebvre** [comment]
Comme l'application a l'air de fonctionner sans cette autorisation et que ça a été refusé par la team de review du Play Store, on ne va juste pas l'implémenter.
